# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CleanInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CleanInterface(object):
    def setupUi(self, CleanInterface):
        CleanInterface.setObjectName("CleanInterface")
        CleanInterface.resize(900, 575)
        self.CleanCard = CardWidget(CleanInterface)
        self.CleanCard.setGeometry(QtCore.QRect(30, 50, 560, 460))
        self.CleanCard.setObjectName("CleanCard")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.CleanCard)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 541, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SubtitleLabel = SubtitleLabel(self.verticalLayoutWidget_2)
        self.SubtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout_2.addWidget(self.SubtitleLabel)
        self.info_table = TableWidget(self.verticalLayoutWidget_2)
        self.info_table.setObjectName("info_table")
        self.info_table.setColumnCount(0)
        self.info_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.info_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_clean = PrimaryPushButton(self.verticalLayoutWidget_2)
        self.start_clean.setObjectName("start_clean")
        self.horizontalLayout.addWidget(self.start_clean)
        self.loadPushButton = PushButton(self.verticalLayoutWidget_2)
        self.loadPushButton.setObjectName("loadPushButton")
        self.horizontalLayout.addWidget(self.loadPushButton)
        self.clean_log = PushButton(self.verticalLayoutWidget_2)
        self.clean_log.setObjectName("clean_log")
        self.horizontalLayout.addWidget(self.clean_log)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.logPlainTextEdit = PlainTextEdit(CleanInterface)
        self.logPlainTextEdit.setGeometry(QtCore.QRect(620, 50, 251, 460))
        self.logPlainTextEdit.setReadOnly(True)
        self.logPlainTextEdit.setBackgroundVisible(False)
        self.logPlainTextEdit.setCenterOnScroll(False)
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")

        self.retranslateUi(CleanInterface)
        QtCore.QMetaObject.connectSlotsByName(CleanInterface)

    def retranslateUi(self, CleanInterface):
        _translate = QtCore.QCoreApplication.translate
        CleanInterface.setWindowTitle(_translate("CleanInterface", "数据清洗界面"))
        self.SubtitleLabel.setText(_translate("CleanInterface", "原始数据"))
        self.start_clean.setText(_translate("CleanInterface", "开始数据清洗"))
        self.loadPushButton.setToolTip(_translate("CleanInterface", "<html><head/><body><p>一般会自动加载，如果没加载出来，可以手动试试</p></body></html>"))
        self.loadPushButton.setText(_translate("CleanInterface", "手动加载数据"))
        self.clean_log.setText(_translate("CleanInterface", "清除日志"))
        self.logPlainTextEdit.setPlainText(_translate("CleanInterface", "欢迎使用数据清理功能！"))
from qfluentwidgets import CardWidget, PlainTextEdit, PrimaryPushButton, PushButton, SubtitleLabel, TableWidget
