# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MdiInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MdiInterface(object):
    def setupUi(self, MdiInterface):
        MdiInterface.setObjectName("MdiInterface")
        MdiInterface.resize(900, 575)
        self.SmoothScrollArea = SmoothScrollArea(MdiInterface)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(0, 50, 900, 480))
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 900, 480))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(900, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mdiArea = QtWidgets.QMdiArea(self.scrollAreaWidgetContents)
        self.mdiArea.setGeometry(QtCore.QRect(0, 0, 900, 480))
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName("mdiArea")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(MdiInterface)
        QtCore.QMetaObject.connectSlotsByName(MdiInterface)

    def retranslateUi(self, MdiInterface):
        _translate = QtCore.QCoreApplication.translate
        MdiInterface.setWindowTitle(_translate("MdiInterface", "Form"))
from qfluentwidgets import SmoothScrollArea
